apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "default"
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
    - name: "default"
      # This receiver just logs alerts to stdout; replace for real notification
      webhook_configs:
      - url: "http://localhost:9999/"
